import { test, expect } from '../src/fixtures/autoHealFixture';
import { runAgentGoal } from '../src/agent/agentRunner';
import { generateSpecFromHistory } from '../src/agent/generator';

test.describe('Autonomous Agentic SDET Suite', () => {
  test('Agent autonomously completes Heroku login workflow', async ({ page }) => {
    const goal =
      'Go to https://the-internet.herokuapp.com/login, log in using username "tomsmith" and password "SuperSecretPassword!", and verify we land on the secure area page.';

    const result = await runAgentGoal(page, {
      goal,
      maxSteps: 8,
    });

    // Validate overall agent execution
    expect(result.success).toBe(true);
    expect(page.url()).toContain('/secure');
    await expect(page.locator('h2')).toContainText('Secure Area');

    // Auto-generate static spec file from successful run trace
    generateSpecFromHistory(
      'Autogenerated Heroku Login Test',
      'tests/generated-login.spec.ts',
      result
    );
  });
});