"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const autoHealFixture_1 = require("../src/fixtures/autoHealFixture");
const agentRunner_1 = require("../src/agent/agentRunner");
const generator_1 = require("../src/agent/generator");
autoHealFixture_1.test.describe('Autonomous Agentic SDET Suite', () => {
    (0, autoHealFixture_1.test)('Agent autonomously completes Heroku login workflow', async ({ page }) => {
        const goal = 'Go to https://the-internet.herokuapp.com/login, log in using username "tomsmith" and password "SuperSecretPassword!", and verify we land on the secure area page.';
        const result = await (0, agentRunner_1.runAgentGoal)(page, {
            goal,
            maxSteps: 8,
        });
        // Validate overall agent execution
        (0, autoHealFixture_1.expect)(result.success).toBe(true);
        (0, autoHealFixture_1.expect)(page.url()).toContain('/secure');
        await (0, autoHealFixture_1.expect)(page.locator('h2')).toContainText('Secure Area');
        // Auto-generate static spec file from successful run trace
        (0, generator_1.generateSpecFromHistory)('Autogenerated Heroku Login Test', 'tests/generated-login.spec.ts', result);
    });
});
