import { test, expect } from '../src/fixtures/autoHealFixture';

test.describe('Generated Agentic Suite', () => {
  test('Autogenerated Heroku Login Test', async ({ page }) => {
    await page.goto('https://the-internet.herokuapp.com/login');
    await page.fill('#broken-username', 'tomsmith');
    await page.fill('#password', 'SuperSecretPassword!');
    await page.click('button');
    await expect(page.locator('h2')).toContainText('Secure Area');
  });
});