"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const autoHealFixture_1 = require("../src/fixtures/autoHealFixture");
autoHealFixture_1.test.describe('Generated Agentic Suite', () => {
    (0, autoHealFixture_1.test)('Autogenerated Heroku Login Test', async ({ page }) => {
        await page.goto('https://the-internet.herokuapp.com/login');
        await page.fill('#username', 'tomsmith');
        await page.fill('#password', 'SuperSecretPassword!');
        await page.click('button');
        await (0, autoHealFixture_1.expect)(page.locator('h2')).toContainText('Secure Area');
    });
});
